version: 2.1

executors:
  default:
    docker:
      - image: phanect/ci-javascript

commands:
  init:
    steps:
      - checkout
      - run: npm install

jobs:
  build:
    executor:
      name: default
    steps:
      - init
      - run: npm test
      - run:
          name: npm run lint
          command: cp ./rwt.example.json ./rwt.json && npm run lint
      - run: npm publish --dry-run --access public --non-interactive

  release:
    executor:
      name: default
    steps:
      - init
      - run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > "$HOME/.npmrc"
          npm run release

workflows:
  version: 2
  build-n-release:
    jobs:
      - build:
          filters: # Run when any branches & tags pushed
            tags:
              only: /.*/
      - release:
          filters:
            tags:
              only: /^v.*/
            # By default, release runs on push to any branches.
            # To avoid running release, it is required to ignore all branches here.
            branches:
              ignore: /.*/
          requires:
            - build
