version: 2

jobs:
  build:
    working_directory: ~/eslint-plugin
    docker:
      - image: phanect/ci-javascript
    steps:
      - run:
          name: System Update
          command: |
            sudo apt-get update -qq
            DEBIAN_FRONTEND=noninteractive sudo apt-get dist-upgrade --yes

            sudo npm install --global npm

      # Test
      - checkout
      - run: yarn install
      - run: yarn test

      - deploy:
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > "$HOME/.npmrc"

            if [[ "${CIRCLE_BRANCH}" = "master" ]]; then
              #
              # If this build is master branch, deploy to npmjs.com
              #
              yarn release
            fi
